name: First Timers
on: [push, pull_request]
jobs:

  test-build:
    name: Test & Build
    runs-on: ubuntu-latest
    steps:
- uses: actions/first-interaction@v1
  with:
    repo-token: ${{ secrets.GITHUB_TOKEN }}
    issue-message: '# Welcome.\n Thank you for creating this issue. We are glad you are here.'
    pr-message: 'Welcome.\n Thank you for this PR.'
